name: Bug Report
description: Create a bug report.
title: "🐞: "
assignees: misspent
labels: ["bug"]
body:
  - type: checkboxes
    id: check
    attributes:
      label: 🔍 Did you check former issues?
      description: "Please check out other issues before continuing. I will close this issue if it's a duplicate."
      options:
      - label: "I have checked other issues"
        required: true
  - type: textarea
    id: browser
    attributes:
      label: "🌐 Browser & OS (specifics)"
      value: |
        Browser: 
        Browser version: 
        Operating System: 
    validations:
      required: true
  - type: dropdown
    id: file-name
    attributes:
      label: 📂 What file/import?
      options:
        - userChrome
        - userContent
        - URL import
  - type: textarea
    id: bug-description
    attributes:
      label: "📝 Describe the bug in detail"
      description: "Please describe the bug. Make sure it's clear and concise."
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "📸 Screenshots"
      description: "If applicable, add screenshots to help give me a bigger picture of the issue at hand (It'll be very convenient and helpful if you do)."
